SAGE:
  ogbl-ddi:
    drop: 0.3     # 0.3-real,
    concat: false

  ogbl-ppa:
    drop: 0
    concat: false

  ogbl-collab:
    drop: 0.0
    concat: false

  ogbl-citation2:
    drop: 0.0
    concat: false

GAT:
  ogbl-ddi:
    drop: 0.3
    concat: true
    n_heads: 1

  ogbl-ppa:
    drop: 0
    concat: true
    n_heads: 1

  ogbl-collab:
    drop: 0
    concat: true
    n_heads: 1

  ogbl-citation2:
    drop: 0
    concat: true
    n_heads: 1